// legacy/src/components/CourseCard.vue
<template>
    <div class="flex flex-col overflow-hidden rounded-lg shadow-lg" style="cursor: pointer;">
        <div class="relative">
            <img class="object-cover w-full h-48" v-lazy="course.thumbnail" alt="Course Thumbnail"
                @click.prevent="showCourse(course.slug)" />
            <div class="absolute top-0 right-0" @click.prevent="handle">
                <div class="flex items-center justify-center w-8 h-8 mt-3 mr-3 bg-white rounded-full"
                    :class="{ 'bg-red text-white': userHasBookmarked }" style="cursor: pointer;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                        class="fill-current bi bi-bookmark" viewBox="0 0 16 16">
                        <path
                            d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z" />
                    </svg>
                </div>
            </div>
            <div class="absolute bottom-0 left-0">
                <div class="flex items-center justify-center w-16 h-8 ml-3 text-center bg-white rounded-t-lg ">
                    <span>
                        <i class="fa fa-eye text-darkblue"></i>
                    </span>
                    <span class="ml-3">{{ course.view }}</span>
                </div>
            </div>
        </div>
        <div class="flex flex-col justify-between flex-1 px-3 py-4 bg-white">
            <div class="">
                <a :href="`/course/${course.slug}/learn`">
                    <p class="text-lg font-medium text-gray line-clamp">
                        {{ course.course_title }}
                    </p>
                </a>
            </div>
            <div class="flex items-center py-4 border-b border-lightgray"
                :class="{ 'pt-11': hasOneLineTitle(course.course_title) }">
                <a href="#" class="w-10">
                    <img class="w-10 h-10 rounded-full" :src="course.author.picture" alt="" />
                </a>
                <div class="ml-3">
                    <p class="text-sm font-medium text-mediumgray">
                        <a href="#" class="hover:underline">
                            {{ course.author.fullname }}
                        </a>
                    </p>
                </div>
            </div>
            <div class="flex items-center justify-end mt-3 text-lg text-gray">
                <!-- <div
          class="flex items-center"
          @click.prevent="upVote"
          style="cursor: pointer"
        >
          <i class="mr-2 fa fa-thumbs-up text-darkblue"></i>
          <span>{{ this.likecount }}</span>
        </div>
        <div
          class="flex items-center"
          @click.prevent="downVote"
          style="cursor: pointer"
        >
          <i class="mr-2 fa fa-thumbs-down text-red"></i>
          <span>{{ this.dislikecount }}</span>
        </div> -->
                <div>
                    <span v-if="!course.is_unlocked">
                        <span v-if="course.is_private">
                            <a href="#"><i class="mr-1 fa fa-lock" style="font-size: 16px"></i>
                                Private</a>
                        </span>
                    </span>
                    <span v-if="!course.is_private">
                        <a href="#">
                            {{ course.isPaid ? "$" + course.formattedPrice : "Free" }}
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    props: ["course"],

    data() {
        return {
            likecount: "0",
            dislikecount: "0",
            userHasLiked: this.course.userHasLiked,
            userHasDisliked: this.course.userHasDisliked,
            course_id: this.course.id,
            userHasBookmarked: this.course.hasBookmarked,
            course_id: this.course.id,
        };
    },
    methods: {
        getVotes() {
            axios
                .get("/course/" + this.course_id + "/countvotes")
                .then((response) => {
                    this.likecount = response.data.like;
                    this.dislikecount = response.data.dislike;
                });
        },
        upVote() {
            if (!this.userHasLiked) {
                axios.get("/course/" + this.course_id + "/like");
                this.likecount++;
                if (this.userHasLiked == false && this.userHasDisliked == false) {
                    this.dislikecount;
                } else {
                    this.dislikecount--;
                }
                this.userHasLiked = true;
                this.userHasDisliked = false;
            }
        },
        downVote() {
            if (!this.userHasDisliked) {
                axios.get("/course/" + this.course_id + "/dislike");
                this.dislikecount++;
                if (this.userHasLiked == false && this.userHasDisliked == false) {
                    this.likecount;
                } else {
                    this.likecount--;
                }
                this.userHasDisliked = true;
                this.userHasLiked = false;
            }
        },

        addToWishlist() {
            axios.post("/course/" + this.course_id + "/create-bookmark");
            this.userHasBookmarked = true;
        },

        removeFromWishlist() {
            axios.delete("/course/" + this.course_id + "/delete-bookmark");
            this.userHasBookmarked = false;
        },

        handle() {
            if (this.userHasBookmarked == true) {
                this.removeFromWishlist();
            } else {
                this.addToWishlist();
            }
        },

        showCourse(slug) {
            window.location.href = `/course/${slug}/learn`;
        },

        formatCourseTitle(title) {
            if (title.length >= 40) {
                return title.substring(0, 40) + '...';
            }

            return title;
        },

        hasOneLineTitle(title) {
            return title.length < 24;
        }
    },
    mounted() {
        // this.getVotes();
    },
};
</script>

<style>
.line-clamp {
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
}
</style>

// src/components/CourseCard.tsx
'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { Bookmark, Eye, Star } from 'lucide-react';

interface Author { picture: string; fullname: string; }
interface Course {
  id: number; slug: string; thumbnail: string; course_title: string; view: number;
  author: Author; userHasLiked: boolean; userHasDisliked: boolean; hasBookmarked: boolean;
  is_unlocked: boolean; is_private: boolean; isPaid: boolean; price?: number;
  formattedPrice: string; level?: string; progress_percentage?: number;
}
interface CourseCardProps { course: Course; }

const CourseCard: React.FC<CourseCardProps> = ({ course }) => {
  const [userHasBookmarked, setUserHasBookmarked] = useState(course.hasBookmarked);

  const toggleBookmark = async (e: React.MouseEvent) => {
    e.preventDefault(); e.stopPropagation();
    try {
      if (userHasBookmarked) {
        await api.delete(`/course/${course.id}/delete-bookmark`);
        setUserHasBookmarked(false);
      } else {
        await api.post(`/course/${course.id}/create-bookmark`);
        setUserHasBookmarked(true);
      }
    } catch {}
  };

  return (
    <div className="flex flex-col bg-white rounded-xl border border-gray-100 hover:border-blue-100 hover:shadow-2xl transition-all duration-500 cursor-pointer group overflow-hidden">
      <div className="relative aspect-video overflow-hidden grayscale group-hover:grayscale-0 transition-all duration-700">
        <Link href={`/course/${course.slug}`}>
          <img
            className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-700"
            src={course.thumbnail}
            alt={course.course_title}
            loading="lazy"
          />
        </Link>
        <div className="absolute bottom-2 left-2 flex items-center gap-1 px-2 py-0.5 bg-black/90 backdrop-blur-md rounded text-[7px] font-black text-white uppercase tracking-widest">
          <Eye size={10} className="text-blue-400" /> {course.view}
        </div>
        <button 
          onClick={toggleBookmark}
          className={`absolute top-2 right-2 w-7 h-7 rounded-lg bg-white/90 backdrop-blur-md flex items-center justify-center transition-all shadow-sm ${userHasBookmarked ? 'text-blue-600' : 'text-gray-400'}`}
        >
          <Bookmark size={12} fill={userHasBookmarked ? 'currentColor' : 'none'} />
        </button>
      </div>
      <div className="flex flex-col p-4">
        <Link href={`/course/${course.slug}`}>
          <h3 className="text-[10px] font-black text-gray-900 leading-[1.2] mb-2 group-hover:text-blue-600 transition-colors line-clamp-2 uppercase tracking-wide">
            {course.course_title}
          </h3>
        </Link>
        <div className="flex items-center gap-2 mb-4">
          <span className="text-[7px] font-black text-gray-400 uppercase tracking-widest">{course.author.fullname}</span>
        </div>
        {course.progress_percentage !== undefined && (
          <div className="mb-4">
            <div className="w-full h-1 bg-gray-50 rounded-full overflow-hidden border border-gray-100">
              <div className="h-full bg-blue-600 rounded-full transition-all duration-1000" style={{ width: `${course.progress_percentage}%` }} />
            </div>
          </div>
        )}
        <div className="flex items-center justify-between mt-auto">
          <div className="flex items-center gap-1">
            <Star size={10} fill="#fb8c00" className="text-[#fb8c00]" />
            <span className="text-[8px] font-black text-gray-900 uppercase">4.8</span>
          </div>
          <div className="text-[10px] font-black text-gray-900 tracking-tighter uppercase italic">
            {course.isPaid ? `$${course.formattedPrice || '49.99'}` : (
              <span className="text-blue-600">Free Access</span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default CourseCard;
